source/assets/components/recipeCard.js, source/assets/components/recipeViewer.js, source/index.html, source/styles/main.css, specs/components/recipeCard/altRecipeCard.css
__WHAT WAS DONE?__
Correctly integrated bootstrap into custom components shadow doms. Additionally, redesigned the recipeCard component, with an emphasis on using Boostrap.
=> Revamp of recipeCard Component + Bootstrap fix

source/assets/scripts/main.js
Fix sorting on recipe card
change order and change functionality
=> Fix Sorting

source/assets/components/recipeCard.js, source/assets/scripts/filter.js, source/index.html, source/styles/main.css, specs/components/recipeCard/altRecipeCard.css, specs/components/recipeViewer/altRecipeViewer.css, specs/components/recipeViewer/altRecipeViewer.html
__What Was Done?__
I updated recipe card to be have a border and nicer margins. In addition I created an alternate recipe viewer that I think would also be a good choice for the recipe viewer. The altRecipeViewer is placed witin specs
=> Recipe Card and Recipe Viewer

source/index.html, source/styles/main.css
__What Was Done?__
So Maggie made changes to navbar. Sadly the changes had to be merged because we took too long to approve the request.
=> Merge Maggie Main

source/index.html, source/styles/main.css
added nav bar for all pages and created flex boxes for filter and search result. Add style for nav bar and filter page.
=> add nav bar and style for filter page.

source/assets/scripts/spoonacular.js
Now in Recipe viewer it will show units of each ingredient in **US metric** units. 
**Please delete this branch after merge!**
=> Display units of ingredients in RecipeViewer

source/assets/scripts/main.js, source/index.html
=> Fixed bug that lead to search filter being shown on home page.

source/index.html, source/styles/main.css
This is the start of a mobile style.  All that is included here is a resizing of the filter checkboxes and background when the viewport is less than 800px wide. Still need to fix the topbar style(using flex probably, complicated by their absolute position originally.  apparently it's best practice to always design for mobile first lol nbd.
=> start to style for mobile

source/assets/scripts/filter.js
=> Ingredients now search with substring

source/assets/_tests_/unit.test.js, source/assets/scripts/testspoonacular.js
name changes,
`thisbettwork.js` ->`copyspoonacular.js`->`testspoonacular.js`
=> unit test name change

source/assets/components/recipeCard/recipeCard.js, source/assets/scripts/Router.js, source/assets/scripts/main.js, source/index.html
Added usage of "ENTER" key in search bar and navSearch bar
Fixed home button does not change Hash URL
Added basic code for button in recipe card(it is commented out)
=> Some quick fix and addition feather

source/assets/scripts/main.js
Added functionality that displays random recipe cards on the home page. Needs design work, but functionality works.
=> Featured recipes

source/assets/components/recipeCard/recipeCard.css, source/assets/components/recipeViewer/recipeViewer.css, source/assets/components/recipeViewer/recipeViewer.js, source/assets/scripts/main.js, source/styles/main.css
This is what I have changed:
1. Add header for instructions and ingredients in the recipe viewer
2. Update background color and change minor styling (color, padding, margin, etc) for : 
-  The main page
- The recipe card 
- Search Result page.
=> Add header for instructions and ingredients. Change style for a few components

source/assets/components/recipeCard/recipeCard.css, source/assets/components/recipeViewer/recipeViewer.css, source/assets/components/recipeViewer/recipeViewer.js, source/assets/scripts/main.js, source/styles/main.css, specs/components/featuredRecipe/featuredRecipe.css, specs/components/featuredRecipe/featuredRecipe.html
I just created a mock-up Recipe Card that is used for the "Featured recipe" section on the main page only. We don't have to use this simplified version of the recipe card. The style of this card is still very basic, but I just want to open a pull request here just so we have an HTML structure of this recipe card somewhere. If we don't want to use it, we don't have to approve this pull request :)
The new files are in `specs/components/featuredRecipes`
=> Recipe Card for "Featured Recipe" section

source/assets/components/recipeCard/recipeCard.css, source/assets/components/recipeCard/recipeCard.js
Added HTML and CSS for the favorite button to the recipe cards.
=> Recipe Card Favorite Burtton

source/assets/components/recipeCard/recipeCard.js, source/assets/scripts/main.js
Added functionality of the button on recipecard
=> Favorite list

source/assets/_tests_/e2e.test.js, source/assets/_tests_/main.e2e.test.js
Added a test that checks functionality of favorite list. resolve #79
=> E2E Test for Fav List

source/assets/components/featuredCard/featuredCard.css, source/assets/components/featuredCard/featuredCard.js, source/assets/scripts/main.js, source/index.html, source/styles/main.css
- Responsive design for the home page
- Responsive design for the featured recipe cards
- Change API key to a functional one
Home Page on mobile view:
=> Responsive Design for the Home Page

source/assets/components/featuredCard/featuredCard.css, source/assets/components/personalShoppingCard/personalShoppingCard.css, source/assets/components/recipeCard/recipeCard.css, source/assets/components/recipeViewer/recipeViewer.css, source/assets/components/shoppingCard/shoppingCard.css, source/assets/scripts/binds/bindShoppingList.js, source/assets/scripts/main.js, source/index.html, source/styles/main.css
What was done
1. Buttons are a lot more interactive
2. Cursor changes to pointer over many of the clickable things on site
3. Shadows given to some buttons and recipeCards
=> Overallstyle

source/assets/components/featuredCard/featuredCard.js, source/assets/components/shoppingCard/shoppingCard.css, source/assets/components/shoppingCard/shoppingCard.js, source/assets/scripts/main.js
Added hover css properties to shopping card recipe titles. Allows the user to realize that they can directly view the recipe using the recipe title. Also fixed a prior commit that was lost in merging, blank dietary icon.
=> Shopping-list-style
